# Generated by Django 4.0.2 on 2022-02-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_pk', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('pub_datetime', models.DateTimeField(null=True)),
                ('thumbnail_default', models.TextField()),
                ('thumbnail_medium', models.TextField()),
                ('thumbnail_high', models.TextField()),
                ('channel_title', models.TextField()),
            ],
        ),
    ]
